# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: ja_ginza
# pipeline: supervised_embeddings

pipeline:
  # - name: "tokenizer_whitespace"
  - name: "nlp_spacy"
  - name: "tokenizer_spacy"
  - name: "CRFEntityExtractor"
  - name: "ner_crf"
  - name: "ner_synonyms"
  # - name: “SpacyEntityExtractor”
  - name: "intent_featurizer_count_vectors"
  - name: "intent_classifier_tensorflow_embedding"

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
